#!/usr/bin/env bash

CONFIG_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/study-mode.conf"
declare -A last_notify_times

service_is_running() {
  systemctl --user is-active --quiet study-mode.service
}

notify_user() {
  notify-send "Study Mode" "$@"
}

show_notification() {
  local msg="$1"
  shift
  notify_user "$msg" --action cancel=Cancel --expire-time 0 "$@"
}

error_out() {
  notify_user "$@"
  exit 1
}

load_config() {
  if [[ ! -f "$CONFIG_FILE" ]]; then
    error_out "Please create the config file \`$CONFIG_FILE\`"
  fi
  mapfile -t BLOCKED <"$CONFIG_FILE"
  if [[ "${#BLOCKED[@]}" -eq 0 ]]; then
    error_out "Your config file contains no items"
  fi
  CONFIG_MTIME=$(stat -c %Y "$CONFIG_FILE")
}

kill_app() {
  local app="$1"
  local last_time="${last_notify_times[$app]:-0}"
  local now
  now=$(date +%s)
  if pkill -TERM -fi "$app"; then
    if ((now - last_time > 10)); then
      notify_user "You can not use \`$app\` right now"
      last_notify_times[$app]=$now
    fi
  fi
}

daemon_loop() {
  load_config

  while true; do
    local current_mtime
    current_mtime=$(stat -c %Y "$CONFIG_FILE" 2>/dev/null)

    if [[ "$current_mtime" != "$CONFIG_MTIME" ]]; then
      load_config
    fi

    for app in "${BLOCKED[@]}"; do
      kill_app "$app"
    done
    sleep 5
  done
}

prompt_loop() {
  if service_is_running; then
    res=$(show_notification "Enabled" --action stop=Stop --wait)
  else
    res=$(show_notification "Disabled" --action start=Start --wait)
  fi

  case "$res" in
  start)
    systemctl --user start --now study-mode
    ;;
  stop)
    systemctl --user stop --now study-mode
    ;;
  *)
    exit 0
    ;;
  esac

  [[ $? -ne 0 ]] && notify_user "Failed to $res study-mode"
}

case "${1:-}" in
--daemon | "")
  daemon_loop
  ;;
--prompt)
  prompt_loop
  ;;
*)
  echo "Usage: study-mode [--daemon|--prompt]"
  exit 1
  ;;
esac

